### ISSUE TITLE
配合viewpager使用的时候，反向滑动，底部的tab会消失。正向就会出现！

### ISSUE THREAD

**Issue by keyboard3** [HomHomLin/AdvancedPagerSlidingTabStrip#3]

**Comment by HomHomLin** [comment]
用的是哪种显示模式？

**Comment by keyboard3** [comment]
view tab  至于底部的。  顺序点击 正常。  反向点击  底部的tab就消失了

**Comment by keyboard3** [comment]
我发现了  我在设置当点击最后一个tab时  让toolbar高度设置为0，然后再点击其他的tab，toolbar在设置正常。tab栏就会消失，不知道是什么问题。。。。。。

**Comment by keyboard3** [comment]
我找到问题了。   谢谢
