### ISSUE TITLE
不知道为什么没有出现下划线的，tab是是设置在上面的

### ISSUE THREAD

**Issue by SYJack** [HomHomLin/AdvancedPagerSlidingTabStrip#4]
贴上设置代码
`<style name="pagertab_style2">
        <item name="apTabBackground">@drawable/tab_bg_transparent</item>
        <item name="android:textSize">18sp</item>
        <item name="android:textAppearance">@style/CustomTabPageIndicator.Text</item>
        <item name="android:textColor">@drawable/tab_color_select</item>
        <item name="apTabIndicatorColor">@color/colorAccent</item>
        <item name="apTabShouldExpand">false</item>
        <item name="apTabPaddingLeftRight">8dp</item>
        <item name="apTabDrawMode">normal</item>
        <item name="apTabTextSelectColor">@color/color_selected_text</item>
    </style>`

**Comment by HomHomLin** [comment]
Try this：
       `<item name="apTabIndicatorHeight">2dp</item>`

**Comment by SYJack** [comment]
可以了，谢谢呀。
